---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: web
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: codeanit/demo-cicd-go:v0.0.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-data
        mountPath: /var/web         
      volumes:
      - name: web-data
        persistentVolumeClaim:
            claimName: web-pv-claim
