kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: web-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv-volume
  labels:
    type: local
spec:
  storageClassName: web-storage
  claimRef:
    name: web-pv-claim
    namespace: web
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/web
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hp

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pv-claim
  namespace: web
spec:
  storageClassName: web-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi